[package]
name = "ttml-parser"
version = "0.1.0"
authors = ["Thomas Lackemann <tommylackemann@gmail.com>"]

[lib]
name = "ttml"
path = "src/lib.rs"

[[bin]]
name = "ttml-parser"
path = "src/main.rs"

[dependencies]
chrono =  { version = "0.4.0", features = [ "serde" ] }
log = "*"
loggerv = "0.4.0"
rand = "0.3"
structopt = "0.1.1"
structopt-derive = "0.1.1"
uuid = { version = "0.4", features = [ "serde", "v4" ] }
