[package]
name = "ttml-parser"
version = "0.1.0"
authors = ["Thomas Lackemann <tommylackemann@gmail.com>"]

[lib]
name = "ttml"
path = "src/lib.rs"

[[bin]]
name = "ttml-parser"
path = "src/main.rs"

[dependencies]
chrono = { version = "0.4.0", features = [ "serde" ] }
error-chain = "0.11.0"
log = "*"
nom = "^3.2"
rand = "0.3"
uuid = { version = "0.4", features = [ "serde", "v4" ] }
serde = "1.0.16"
serde_json = "1.0.4"
serde_derive = "1.0.16"
